<?php

use function Livewire\Volt\{title};

title('Abwesenheit - Übersicht');

?>

<x-intranet-app-abwesenheit::abwesenheit-layout heading="Abwesenheit App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-abwesenheit::abwesenheit-layout>